oc_cms_homepage:
    path:     /
    defaults: { _controller: OCCmsBundle:Page:index }

oc_cms_pages:
    path:     /pages
    defaults: { _controller: OCCmsBundle:Page:pages }

create:
    resource: "@OCCmsBundle/Controller/PageController.php"
    type:     annotation