oc_cms_homepage:
    path:     /
    defaults: { _controller: OCCmsBundle:Page:index }

oc_cms_pages:
    path:     /pages
    defaults: { _controller: OCCmsBundle:Page:pages }


oc_cms_create_page:
    path:     /page/create
    defaults: { _controller: OCCmsBundle:Page:create }


oc_cms_create_category:
    path:     /page/category
    defaults: { _controller: OCCmsBundle:Page:addCategory }


oc_cms_update_page:
    path:     /page/{id}/edit
    defaults: { _controller: OCCmsBundle:Page:update }
    requirements:
        id: \d+

oc_cms_delete_page:
    path:     /page/{id}/delete
    defaults: { _controller: OCCmsBundle:Page:delete }
    requirements:
        id: \d+

oc_cms_read_page:
    path:     /page/{category}/{slug}
    defaults: { _controller: OCCmsBundle:Page:read }
    requirements:
        category: "[a-zA-Z0-9-_/]+"
        slug: "[a-zA-Z0-9-_/]+"
